try to include custom `id` and `beforeId` props
RodrigoHamuy/react-three-map pull request #70
Opened 2023-10-19 14:09 UTC by iduuck

2023-10-19 14:39 UTC, RodrigoHamuy commented on src/api/canvas-props.ts
> +  id?: string;
You think in here ([link](https://github.com/RodrigoHamuy/react-three-map/blob/main/src/core/use-canvas.ts#L7)) we can do the following, please?

```ts
export interface useCanvasProps extends Omit<CanvasProps, 'id'|'beforeId'> {
```

2023-10-19 14:40 UTC, RodrigoHamuy commented on src/mapbox/canvas.tsx
>    const { id, onAdd, onRemove, render } = useCanvas({ ...props, fromLngLat });
Can we do this on line 11? So we don't pass these new properties down.
```ts
export const Canvas = memo<CanvasProps>(({id, beforeId...props}) => {
```

2023-10-19 14:43 UTC, RodrigoHamuy requested changes
Thanks for doing this ❤️ . Would it be possible to go through my comments and also add a changeset minor file (`yarn changeset` or follow [GH comment ](https://github.com/RodrigoHamuy/react-three-map/pull/70#issuecomment-1771071932) last link)? Thank you 🙏

2023-10-24 14:37 UTC, RodrigoHamuy commented
Thanks for doing this! Added a minor change and will be releasing soon https://github.com/RodrigoHamuy/react-three-map/pull/76

2023-10-24 14:37 UTC, RodrigoHamuy commented
Thanks for doing this! Added a minor change and will be releasing soon https://github.com/RodrigoHamuy/react-three-map/pull/76

2023-10-24 14:37 UTC, closed without merging

2023-10-27 09:00 UTC, iduuck commented
Thanks for the changes, didn't had the free time to tackle those. Sorry.